### PR TITLE
map review tool export

### PR DESCRIPTION
**Pull request by tghoward**
New script for exporting to format needed for map review tool. Script placed within a new folder "postprocessing"  @ChristopherTracey since aquatic doesn't use `raster` there will be a small amount of alterations for aquatic, but not too much. Perhaps tweak so the it chooses between the model type/style within the script, then it will be more portable to master?

### CODE REVIEW

**Comment by tghoward** [comment]
This script requires the user to run the bottom (debugging) part of script 0 right now, but could be tweaked to include it as the final script to run wrapper?

**Comment by tghoward** [comment]
drat. RStudio hangs (won't close) after using reticulate. Looking for a solution.

**Comment by tghoward** [comment]
posted issue here: https://github.com/rstudio/reticulate/issues/415

**Comment by ChristopherTracey** [comment]
This code will replicate most of that python part of your script (lines 58-68) using the R bridge:

```
library(arcgisbinding)
arc.check_product()
# copy over a blank gdb as the bridge can't create them by itself. I would store this in some other directory
shell(paste('Xcopy /E /I  blank.gdb predictedhabitat-poly.gdb'))
# write the results
arc.write(paste0("predictedhabitat-poly.gdb","/",model_species,"_mtpg"), inShp)
```

As noted, the bridge can't write a gdb on its own, so I just created a blank gdb that can be stored somewhere and copied over and placed in the model review output folder as "predictedhabitat-poly.gdb".

**Comment by tghoward** [comment]
Ok, good, thanks. How much do you need to install?

**Comment by tghoward** [comment]
I think I got it figured out. Thanks @ChristopherTracey

**Comment by ChristopherTracey** [comment]
If this means you're using the r-arcgis bridge, you've made my weekend ;)

**Pull request merged**
