### PR TITLE
WIP grouping points

### PR DESCRIPTION
**Pull request by tghoward**
Figuring out how to group observations. This is an initial foray. @ChristopherTracey @dnbucklin I think this would only apply to terrestrial so I'm suggesting it gets pulled only there. I know I'm going to get confused as to the best way to handle these three branches!

### CODE REVIEW

**Comment by ChristopherTracey** [comment]
If we're using EO separation distance as the distance for grouping EOs, we could have NS provide that value via a Biotics export that we could include in the SQLite database (per species). Then we wouldn't have to set it each time.

For the record, here is the current code for aquatic grouping: [https://github.com/PNHP/SDM_Tools/tree/master/aquatic_grouping_tool](https://github.com/PNHP/SDM_Tools/tree/master/aquatic_grouping_tool). It's written in ArcPy and makes heavy use of some of the ArcGIS network functions. I'm not sure if we're going to find a R-based solution for it in the near future.

**Comment by tghoward** [comment]
Interesting, I installed nhSDM and was all set to go that route but a timing test suggests it is much slower than using the GIS operations in "version 2".  Perhaps we won't even use separation distances but instead group by an overlaying grid ...

**Comment by tghoward** [comment]
... but looking forward to using nhSDM for other uses!

**Comment by dnbucklin** [comment]
Good to know. I used `st_distance` method rather than the buffer/union method in `nh_group`. I knew this was slower but hadn't tested on really large datasets, so I hadn't noticed the speed difference too much. I think I went that route to provide a more generic solution that could handle any input projection (most importantly WGS84).

**Pull request merged**
