### PR TITLE
re-factor script 1 to use sf

### PR DESCRIPTION
**Pull request by tghoward**
converted all of script 1_pointsInPolys_cleanBkgPts.R to package sf.   Also did some work on moving towards using here(). So script 0 (which is superceded) and user_run_SDM came along for the ride.  Those will continue to be a bit dynamic, I expect.

### CODE REVIEW

**Comment by dnbucklin** [comment]
@tghoward I think this is `terrestrial` branch only for now?

**Comment by tghoward** [comment]
@dnbucklin I could do that, but I'm not sure why?

**Comment by dnbucklin** [comment]
I guess at this point, it doesn't matter much at this point regarding which branch; we should update aquatic with `sf` too at some point.

I noticed you remove the `baseName` naming for the files...I'm not sure if that's just for testing but I really think that should stay; it functions for archiving and allows us to always recall the exact dataset used for a particular model.

Also there's a merge conflict remnant (`<<<<<<< HEAD`) at line 34 in script 1.

**Comment by tghoward** [comment]
Added usages of baseName back in and merged in the changes you just pushed.  I did not, however, keep in the lines where a copy of the file is written (deleted line 55). Since we are writing out copies of the files that actually are used, I didn't see the reasoning for that. Is that what you were referring to?

**Comment by dnbucklin** [comment]
Right line 55 was an archive of the original input presence file, with the thinking that the true original (the file assigned to `nm_presFile`) could get over-written but we'd still have the exact file used in any given model. 

But I guess the `[baseName]_expl` file covers this well enough. I'm fine with removing it. It originated with the aquatics so it may have been more relevant in that case.

**Comment by tghoward** [comment]
Tested again and cleaned up to run better with `user_run_SDM`. Also removed the `exists` test.

**Pull request merged**
