### PR TITLE
new folder structure with here(); set up sqliteDB to work with it

### PR DESCRIPTION
**Pull request by tghoward**

### CODE REVIEW

**Comment by tghoward** [comment]
@ChristopherTracey @dnbucklin (testing out this communication system), so last week I started moving the scripts over to use here(). In terms of organization, the most significant change is that folders need to be nested within the project's root directory in order to use here's functionality easily. I think we can do this with most of the data, but not the env vars, so there will be some exceptions. The way to keep data from git, then, would be to use .gitignore files. 

How do you two feel about this change? I've written it to master, but I could back it up if you think going this route is not productive.  More on here(), here:

https://github.com/jennybc/here_here

**Comment by dnbucklin** [comment]
I like `here()` and removing `setwd` calls as much as possible. I think it especially makes a lot of sense in these preproc scripts that call files/scripts from within this git repo.

Related to this, on the modelling procedure itself I made some recent changes to aquatic (554bc05) which use a new `loc_model` argument to specify the project folder, and all input/output modelling folders/files are created within that folder (if they don't already exist); this makes no existing file structure necessary. I think this could integrate well with your `_data` approach to storing inputs/outputs and when I get the time I can make the same update for terrestrial/master.

**Comment by tghoward** [comment]
@dnbucklin Ok, sounds good. I'll look into the `loc_model` argument and see if `.gitignore` can still take care of it.

**Comment by dnbucklin** [comment]
The way I'd set it up I think `loc_model` could be set to `_data/species`, so all that's necessary repository-wise would be: 

- _data
   - /databases
   - /species

And ignore everything else (files, other folders, etc).

**Comment by ChristopherTracey** [comment]
I'm late to the party on this, but I'll say that I like here() and I agree with the approach on this.

**Pull request merged**
