### PR TITLE
use mobi-tracker on SQL Server

### PR DESCRIPTION
**Pull request by tghoward**
use SQL Server instead of Access DB. We can't seem to save connection pwds in ODBC setup so change system to no longer require a previously defined ODBC connection but use a local text file with connection information that does not sync up to github.

### CODE REVIEW

**Comment by tghoward** [comment]
@ChristopherTracey @memoore This change is significant in that it hits on the (new) back end DB for Mobi Tracker. When you pull it in, you'll need to have a properly configured copy of this text file ( on mobi01: F:\tracking_database\mobi_tracker_connection_string_short.dsn  on mobiprep: N:\tracking_database\mobi_tracker_connection_string_short.dsn)

@matthewpaulking I think I'm changing my mind in that perhaps you should also be using the same backend instead of having your own copy of this DB. Especially in that your models will be used in the final product. So let's talk more about that.

**Comment by matthewpaulking** [comment]
Sounds good @tghoward. Looks like we need to set up some credentials to connect to the db? It might be nice to work on a local copy just to get some test runs going, and then switch to the shared db once we are ready. What to you think?

**Comment by ChristopherTracey** [comment]
@matthewpaulking, was this the credential error you were getting?
`Error: nanodbc/nanodbc.cpp:950: 28000: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Login failed for user 'Chris_Tracey'.`
If so, I'm getting it as well.

Also, I added `odbc` to the package check script.  You all should pull in b921724 from the aquatic branch.

**Comment by ChristopherTracey** [comment]
Also, in case this is related to the credential issue, but when I try to open the MoBItracker db on MoBI01, it will only open as read-only and when I try to open the form, I  get an ODBC error about the connection to MoBI tracker failing.

**Comment by ChristopherTracey** [comment]
> If so, I'm getting it as well.
 
Nevermind, I forgot to change the 'random user name' in the password.

**Pull request merged**
